server:
    port: 8088
    
spring:
    datasource:
        name: getData
        url: jdbc:mysql://localhost:3306/log_data?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        #\u4F7F\u7528druid\u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
        
mybatis:
    mapper-locations: classpath:com/huiyingxiao/logData/mapper/*.xml
    type-aliases-package: com.huiyingxiao.logData.pojo

mapper:
    mappers: com.huiyingxiao.logData.mapper
    not-empty: false
    identity: MYSQL

logging:
  level:
    com:
      huiyingxiao:
        logData:
            mapper: debug